#include<stdio.h>

int main(){
    int i,j,arr[10]={1,2,3};  // 10 memory location allocated FROM stack during runtime
    //ALL ALLOCATION DONE AT COMPILE TIME IS STATIC MEMORY ALLOCATION
    
    /*MEMORY ASSIGNED AT COMPILE TIME MEANS MEMORY DECIDING WHICH AMT OF MEMORY GIVEN TO WHAT 
    AND IS NOT ALLOCATED AT START AND THIS DECISION CANT BE CHANGED DURING RUNTIME
    */

    /*AT RUNTIME IF I ADD ELEMENTS GREATER THAN IT CAN STORE IT WILL CAUSE
    BUFFER OVERFLOW WHICH IS DRAWBACK OF ARRAY AS ARRAY IS FIXED*/

    /*TO OVERCOME THIS DRAWBACK WE USE DYNAMIC MEMORY ALLOCATION
      malloc();  calloc();  realloc();   free();  4 functions*/
    
    /*NOW FOR DYNAMIC MEMORY ALLOCATION IT WILL BE ALLOCATED FROM HEAP AND NOT STACK*/

    /*STATIC MEMORY ALLOCATION ------>  STORED FROM STACK
      DYNAMIC MEMORY ALLOCATION -----> STORED FROM HEAP*/
    
      

    
    return 0;
}