/*File redirection steps :

a.exe > filrname.txt
a.exe < filename.txt

*/

/*
INTRO:

< (operator) used in cmd line to redirect input from a file to a program. It allows you to take input for a program from a file instead of typing it manually in the command prompt.

When you use the < operator, the contents of the specified file are fed as input to the program. This is particularly useful when you have a program that requires user input, and you want to automate the process by providing the input from a file.

> (operator) used in cmd line to redirect output from a program to a file. It allows you to save the output of a program to a file instead of displaying it on the console.

When you use the > operator, the output generated by the program is written to the specified file. If the file already exists, it will be overwritten. If the file does not exist, it will be created. This is useful for saving the results of a program or for logging purposes.  


a.exe < input.txt > output.txt  (input.txt is the file from which a.exe will read input, and output.txt is the file where a.exe will write its output)
*/


#include <stdio.h>

int main(){
    int a[100] , n;

    
    scanf("%d",&n);
    printf("\n\nPrint the %d elements:\n",n);
    for (int i = 0; i < n; i++)
    {
        scanf("%d ",&a[i]);
    }
    printf("\n");
    for (int i = 0; i < n; i++)
    {
        printf("%d ",a[i]);
    }
    return 0;
}